language: ruby
rvm:
- 2.4.1
branches:
  only:
  - master
scripts:
- bundle exec rake build
before_install:
- eval `ssh-agent -s`
- chmod 600 ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_0cf64fab5b09_key -iv $encrypted_0cf64fab5b09_iv
  -in deploy_key.enc -out deploy_key -d
- cp deploy_key ~/.ssh/
- chmod 600 ~/.ssh/deploy_key
- ssh-add ~/.ssh/deploy_key
- echo -e "Host skoji.jp\n\tPort 2222\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- build/travis-deploy.sh
notifications:
  slack:
    email: false
    secure: E/wR0dV1SAMUQ0KcX5blAoi2cDRCZEERqe99HbRJSIIbKgEx/0K59UcpuDmnif8CtgRXJO0xLpYUNaxQpUxtW1zrgTPPrb15iJlfncgTVFIBN8HXVjzbWk+GnHZVz+g0xoB2nZD5+o4Nk0qAS6bSGLhQ6XEWSy8/9E6XplyFkGwg9LpjyrD86kpV+fAnwCVdRGPOXcXAIIrgJlc0fU2KdjA6TgEuDEYN0gjzrFb0K3ldjDlbBjJNLq7XCqfsQNnZ3PXe3Lni9fxr9MtLscGf+hgwelfIU96HkBQGSWVhnyE0frdDaoBqUeI5Fvr0tSPVMz8Tajv/Zc6sjOrAqF6Tx1wqBDiNbITxp7qlSw0B/3/RkEs83ZzwkrP9X91HN4tVRVwSwc+KatBheszXwzTDFeysGbd1ILoJ1xp87kie5an3TYINhYJUgjJQDY+inkOcz3+o7RcD+pqUkZ5YNu2qYv/eqn41VCIS5Rl1O58IBxjxxZUT0EgDgoHV9r9zW66eKlQzlKWoVTHmP1BDaN4M23mdpxJRKoel++Q9okVx8zT48ZVc74KK0SlzhWT6BNOhPv1kYLLZRVBmN37VIHIfkJa2HaTwSrDI04E6AGmnKlelyXVAXv6GxtwM/6ItdEG1cH9HXtDZXSJoJSIiLjvTlvQpXt3LzY7ZdjminiVGBNE=
