language: ruby
rvm:
- 2.4.1
branches:
  only:
  - master
scripts:
- bundle exec rake build
before_install:
- eval `ssh-agent -s`
- chmod 600 ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_0cf64fab5b09_key -iv $encrypted_0cf64fab5b09_iv
  -in deploy_key.enc -out deploy_key -d
- cp deploy_key ~/.ssh/
- chmod 600 ~/.ssh/deploy_key
- ssh-add ~/.ssh/deploy_key
- echo -e "Host skoji.jp\n\tPort $PORT\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- build/travis-deploy.sh
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    secure: E/wR0dV1SAMUQ0KcX5blAoi2cDRCZEERqe99HbRJSIIbKgEx/0K59UcpuDmnif8CtgRXJO0xLpYUNaxQpUxtW1zrgTPPrb15iJlfncgTVFIBN8HXVjzbWk+GnHZVz+g0xoB2nZD5+o4Nk0qAS6bSGLhQ6XEWSy8/9E6XplyFkGwg9LpjyrD86kpV+fAnwCVdRGPOXcXAIIrgJlc0fU2KdjA6TgEuDEYN0gjzrFb0K3ldjDlbBjJNLq7XCqfsQNnZ3PXe3Lni9fxr9MtLscGf+hgwelfIU96HkBQGSWVhnyE0frdDaoBqUeI5Fvr0tSPVMz8Tajv/Zc6sjOrAqF6Tx1wqBDiNbITxp7qlSw0B/3/RkEs83ZzwkrP9X91HN4tVRVwSwc+KatBheszXwzTDFeysGbd1ILoJ1xp87kie5an3TYINhYJUgjJQDY+inkOcz3+o7RcD+pqUkZ5YNu2qYv/eqn41VCIS5Rl1O58IBxjxxZUT0EgDgoHV9r9zW66eKlQzlKWoVTHmP1BDaN4M23mdpxJRKoel++Q9okVx8zT48ZVc74KK0SlzhWT6BNOhPv1kYLLZRVBmN37VIHIfkJa2HaTwSrDI04E6AGmnKlelyXVAXv6GxtwM/6ItdEG1cH9HXtDZXSJoJSIiLjvTlvQpXt3LzY7ZdjminiVGBNE=
env:
  global:
    secure: k0qzUX2FDd5r0yzvavCRMeabzACPkaEKnCzqWLITOa3Ciq3JjQR5me+iCTWopI0Tz3++JC9nXq3uEf3w9TrZtdY4cM8LjI+TCuzrgMsteE06gjfnf+2BWxkYnkLoQufMilXURgDGKfk25mit4wnM5m9KyZ9tQ6gQDQGTIn+UoQLVGlJ/ET265iTQjbfFg5iuCcvo+7g1KuNeHmdrB93k4lEOIbFS33PXDnv8jy9f7I8ICL1ig7l98nINV1oHiFLGzU7Ojo/C0yTp3a1B4QtkPNkoC8/fEsEvdp2l2SmxSjNioFaSUJS4ZP8sG/IrZl/1MBPFRpDRZOjTOO9cEi66KllVBNEehacPvjskl70KSl3b84sDjzkawnzOtLN9mF54+lPkdCbpvM92EZEsN+Xnk5yBaqczmIFxSeDoysXkSRzbYgFg9tW/LxYqkQ5AMMb26U/6thTDn+mgJlXt2dGFCvT4viN0JnGTUvDjbx6JOuwDpCfl0N1hBbOQ4tTyJhl6coVBcI33b8+M3k4Y8WWMOIOHzPYPYj+5UfC9uNDCDFqprzExq1DQxHiJLNxNeiXGGQzL0HoEvzpDD+KTpsFbwRVcDN5VIRTo+mBZVeMAXiRLuwwq8T2gzVAIY9sNuI2HR8MC7bUMujdd91muEO/qeEte203RyvguYQoq0DRe5Qs=
