#!/bin/sh
if [ $# -ne 1 ]; then
   echo "You should specify post title." 1>&2
   exit 1;
fi
pushd `dirname $0` > /dev/null
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n `bundle exec jekyll post $1 | grep 'New post created' | sed 's/New post created at \(.*\)\./\1/'`
popd > /dev/null
